export const GET_FLOORS = 'GET_FLOORS';
export const GET_FLOORS_SUCCESS = 'GET_FLOORS_SUCCESS';
export const GET_FLOORS_FAILURE = 'GET_FLOORS_FAILURE';

export function getFloorsAction() {
  return {
    type: GET_FLOORS,
  };
}

export function getFloorsSuccessAction(floors) {
  return {
    type: GET_FLOORS_SUCCESS,
    payload: { floors },
  };
}

export function getFloorsFailureAction() {
  return {
    type: GET_FLOORS_FAILURE,
  };
}

const initialState = {
  loading: false,
  failure: false,
  success: false,
  floors: {
    '1': {
      name: '1',
      buildingId: 'academicBuilding',
      meterPerPixel: 0.0455,
      mapWidth: 4400,
      mapHeight: 3200,
      ratio: 0.1,
      defaultX: 2228,
      defaultY: 1499,
      defaultLevel: 0,
    },
    '2': {
      name: '2',
      buildingId: 'academicBuilding',
      meterPerPixel: 0.0455,
      mapWidth: 4800,
      mapHeight: 3400,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 3476,
      defaultY: 1247,
    },
    '3': {
      name: '3',
      buildingId: 'academicBuilding',
      meterPerPixel: 0.0455,
      mapWidth: 4800,
      mapHeight: 3400,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 1556,
      defaultY: 849,
    },
    '4': {
      name: '4',
      buildingId: 'academicBuilding',
      meterPerPixel: 0.0455,
      mapWidth: 4800,
      mapHeight: 3400,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 1556,
      defaultY: 849,
    },
    '5': {
      name: '5',
      buildingId: 'academicBuilding',
      meterPerPixel: 0.0455,
      mapWidth: 4800,
      mapHeight: 3400,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 1556,
      defaultY: 849,
    },
    '6': {
      name: '6',
      buildingId: 'academicBuilding',
      meterPerPixel: 0.0455,
      mapWidth: 4800,
      mapHeight: 3400,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 1556,
      defaultY: 849,
    },
    '7': {
      name: '7',
      buildingId: 'academicBuilding',
      meterPerPixel: 0.0455,
      mapWidth: 4800,
      mapHeight: 3400,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 1556,
      defaultY: 849,
    },
    UC1: {
      name: '1',
      buildingId: 'universityCenter',
      meterPerPixel: 0.0455,
      mapWidth: 2000,
      mapHeight: 1400,
      ratio: 0.15,
      defaultLevel: 0,
      defaultX: 847,
      defaultY: 526,
    },
    UCG: {
      name: 'G',
      buildingId: 'universityCenter',
      meterPerPixel: 0.0455,
      mapWidth: 2000,
      mapHeight: 1400,
      ratio: 0.15,
      defaultLevel: 0,
      defaultX: 847,
      defaultY: 526,
    },
    IASG: {
      name: 'G',
      buildingId: 'ias',
      meterPerPixel: 0.0455,
      mapWidth: 1200,
      mapHeight: 1200,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 639,
      defaultY: 575,
    },
    IAS1: {
      name: '1',
      buildingId: 'ias',
      meterPerPixel: 0.0455,
      mapWidth: 1200,
      mapHeight: 1200,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 639,
      defaultY: 575,
    },
    IAS2: {
      name: '2',
      buildingId: 'ias',
      meterPerPixel: 0.0455,
      mapWidth: 1200,
      mapHeight: 1200,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 639,
      defaultY: 575,
    },
    IAS3: {
      name: '3',
      buildingId: 'ias',
      meterPerPixel: 0.0455,
      mapWidth: 1200,
      mapHeight: 1200,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 639,
      defaultY: 575,
    },
    IAS4: {
      name: '4',
      buildingId: 'ias',
      meterPerPixel: 0.0455,
      mapWidth: 1200,
      mapHeight: 1200,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 639,
      defaultY: 575,
    },
    IAS5: {
      name: '5',
      buildingId: 'ias',
      meterPerPixel: 0.0455,
      mapWidth: 1200,
      mapHeight: 1200,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 639,
      defaultY: 575,
    },
    NABG: {
      name: 'G',
      buildingId: 'lsk',
      meterPerPixel: 0.0455,
      mapWidth: 2600,
      mapHeight: 1600,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 1332,
      defaultY: 913,
    },
    NAB1: {
      name: '1',
      buildingId: 'lsk',
      meterPerPixel: 0.0455,
      mapWidth: 2600,
      mapHeight: 1600,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 1089,
      defaultY: 537,
    },
    NAB2: {
      name: '2',
      buildingId: 'lsk',
      meterPerPixel: 0.0455,
      mapWidth: 2600,
      mapHeight: 1600,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 1089,
      defaultY: 537,
    },
    NAB3: {
      name: '3',
      buildingId: 'lsk',
      meterPerPixel: 0.0455,
      mapWidth: 2600,
      mapHeight: 1600,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 1089,
      defaultY: 537,
    },
    NAB4: {
      name: '4',
      buildingId: 'lsk',
      meterPerPixel: 0.0455,
      mapWidth: 2600,
      mapHeight: 1600,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 1089,
      defaultY: 537,
    },
    NAB5: {
      name: '5',
      buildingId: 'lsk',
      meterPerPixel: 0.0455,
      mapWidth: 2600,
      mapHeight: 1600,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 562,
      defaultY: 437,
    },
    NAB6: {
      name: '6',
      buildingId: 'lsk',
      meterPerPixel: 0.0455,
      mapWidth: 2600,
      mapHeight: 1600,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 1089,
      defaultY: 537,
    },
    NAB7: {
      name: '7',
      buildingId: 'lsk',
      meterPerPixel: 0.0455,
      mapWidth: 2600,
      mapHeight: 1600,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 1089,
      defaultY: 537,
    },
    CYTG: {
      name: 'G',
      buildingId: 'cyt',
      meterPerPixel: 0.0455,
      mapWidth: 2000,
      mapHeight: 1400,
      ratio: 0.15,
      defaultLevel: 0,
      defaultX: 1001,
      defaultY: 593,
    },
    CYTUG: {
      name: 'UG',
      buildingId: 'cyt',
      meterPerPixel: 0.0455,
      mapWidth: 2000,
      mapHeight: 1400,
      ratio: 0.15,
      defaultLevel: 0,
      defaultX: 1001,
      defaultY: 593,
    },
    CYT1: {
      name: '1',
      buildingId: 'cyt',
      meterPerPixel: 0.0455,
      mapWidth: 2000,
      mapHeight: 1400,
      ratio: 0.15,
      defaultLevel: 0,
      defaultX: 1001,
      defaultY: 593,
    },
    CYT2: {
      name: '2',
      buildingId: 'cyt',
      meterPerPixel: 0.0455,
      mapWidth: 2000,
      mapHeight: 1400,
      ratio: 0.15,
      defaultLevel: 0,
      defaultX: 1001,
      defaultY: 593,
    },
    CYT3: {
      name: '3',
      buildingId: 'cyt',
      meterPerPixel: 0.0455,
      mapWidth: 2000,
      mapHeight: 1400,
      ratio: 0.15,
      defaultLevel: 0,
      defaultX: 1001,
      defaultY: 593,
    },
    CYT4: {
      name: '4',
      buildingId: 'cyt',
      meterPerPixel: 0.0455,
      mapWidth: 2000,
      mapHeight: 1400,
      ratio: 0.15,
      defaultLevel: 0,
      defaultX: 1001,
      defaultY: 593,
    },
    CYT5: {
      name: '5',
      buildingId: 'cyt',
      meterPerPixel: 0.0455,
      mapWidth: 2000,
      mapHeight: 1400,
      ratio: 0.15,
      defaultLevel: 0,
      defaultX: 1001,
      defaultY: 593,
    },
    CYT6: {
      name: '6',
      buildingId: 'cyt',
      meterPerPixel: 0.0455,
      mapWidth: 2000,
      mapHeight: 1400,
      ratio: 0.15,
      defaultLevel: 0,
      defaultX: 1001,
      defaultY: 593,
    },
    CYT7: {
      name: '7',
      buildingId: 'cyt',
      meterPerPixel: 0.0455,
      mapWidth: 2000,
      mapHeight: 1400,
      ratio: 0.15,
      defaultLevel: 0,
      defaultX: 1001,
      defaultY: 593,
    },
    Overall: {
      name: '',
      buildingId: 'campusMap',
      meterPerPixel: 0.0455,
      mapWidth: 2200,
      mapHeight: 1800,
      ratio: 0.1,
      defaultX: 936,
      defaultY: 654,
      defaultLevel: 0,
    },
    G: {
      name: 'G',
      buildingId: 'academicBuilding',
      meterPerPixel: 0.0455,
      mapWidth: 4800,
      mapHeight: 3400,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 2182,
      defaultY: 2343,
    },
    LG1: {
      name: 'LG1',
      buildingId: 'academicBuilding',
      meterPerPixel: 0.0455,
      mapWidth: 4400,
      mapHeight: 3200,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 2078,
      defaultY: 734,
    },
    LG3: {
      name: 'LG3',
      buildingId: 'academicBuilding',
      meterPerPixel: 0.0455,
      mapWidth: 3400,
      mapHeight: 2600,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 1920,
      defaultY: 150,
    },
    LG4: {
      name: 'LG4',
      buildingId: 'academicBuilding',
      meterPerPixel: 0.0455,
      mapWidth: 3200,
      mapHeight: 2400,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 1873,
      defaultY: 180,
    },
    LG5: {
      name: 'LG5',
      buildingId: 'academicBuilding',
      meterPerPixel: 0.0455,
      mapWidth: 3200,
      mapHeight: 2400,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 2050,
      defaultY: 140,
    },
    LG7: {
      name: 'LG7',
      buildingId: 'academicBuilding',
      meterPerPixel: 0.0455,
      mapWidth: 3200,
      mapHeight: 1600,
      ratio: 0.1,
      defaultLevel: 0,
      defaultX: 1290,
      defaultY: 290,
    },
  },
  buildingIds: ['campusMap', 'universityCenter', 'academicBuilding', 'cyt', 'lsk', 'ias'],
  buildings: {
    campusMap: { name: 'Campus Map', floorIds: ['Overall'] },
    universityCenter: { name: 'University Center', floorIds: ['UC1', 'UCG'] },
    academicBuilding: {
      name: 'Academic Building',
      floorIds: ['7', '6', '5', '4', '3', '2', '1', 'G', 'LG1', 'LG3', 'LG4', 'LG5', 'LG7'],
    },
    cyt: {
      name: 'CYT',
      floorIds: ['CYT7', 'CYT6', 'CYT5', 'CYT4', 'CYT3', 'CYT2', 'CYT1', 'CYTUG', 'CYTG'],
    },
    lsk: {
      name: 'LSK',
      floorIds: ['NAB7', 'NAB6', 'NAB5', 'NAB4', 'NAB3', 'NAB2', 'NAB1', 'NABG'],
    },
    ias: {
      name: 'IAS',
      floorIds: ['IAS5', 'IAS4', 'IAS3', 'IAS2', 'IAS1', 'IASG'],
    },
  },
};

const floors = (state = initialState, { type, payload }) => {
  switch (type) {
    case GET_FLOORS:
      return {
        ...initialState,
        loading: true,
      };
    case GET_FLOORS_SUCCESS:
      return {
        ...state,
        loading: false,
        success: true,
        failure: false,
        floors: payload.floors,
      };
    case GET_FLOORS_FAILURE:
      return {
        ...state,
        loading: false,
        success: false,
        failure: true,
      };
    default:
      return state;
  }
};

export default floors;
